### PR TITLE
Add a badge as a link to the Firefox extension on addons.mozilla.org

### PR DESCRIPTION
**Pull request by torokati44**
For lack of a better (official) name, I just called this store "addons.mozilla.org" - which is what AMO is short for.

~The icon is from https://blog.mozilla.org/addons/2015/11/10/promote-your-add-ons-with-the-get-the-add-on-button/, referenced by https://discourse.mozilla.org/t/firefox-add-ons-badge/21088/2.~ Replaced by an edited version of the SVG one linked below.

While ~it's not an SVG, and~ **(it is now)** ~the light blue also clashes with the background a bit~ **(not anymore)**, this is the best I could do, given that I'm more of a developerator than a designerizer.

### CODE REVIEW

**Review by adrian17 — APPROVED** [review]

**Comment by ok-miskit** [comment]
Hey!
I was able to find an SVG version on [https://extensionworkshop.com/documentation/publish/promoting-your-extension/](https://extensionworkshop.com/documentation/publish/promoting-your-extension/).

Direct link to SVG: [https://blog.mozilla.org/addons/files/2020/04/get-the-addon-fx-apr-2020.svg](https://blog.mozilla.org/addons/files/2020/04/get-the-addon-fx-apr-2020.svg)

**Comment by torokati44** [comment]
Cool, thanks! Let me replace the png with that real quick.
Also, what do y'all think, would it be okay to change that background color to something more fitting? And/or the text color? Should be straightforward in an SVG... But "morally"?

**Comment by yakagami** [comment]
> would it be okay to change that background color to something more fitting? And/or the text color? Should be straightforward in an SVG... But "morally"?

To be clear the issue is that the svg belongs to Mozilla and maybe we shouldn't alter it without their permission, right? 

From that link (at the bottom of the website):
> Portions of this content are ©1998–2021 by individual mozilla.org contributors. Content available under a Creative Commons license. 

Unfortunately the exact license isn't specified, but I think it is implied that it isn't a NoDerivatives variant, because that would be specified specifically. That's I see it from a legal perspective.

From a moral perspective the whole reason they made the svg is so people use it to promote their web store. The svg itself doesn't bring them any monetary benefit so I think from a strictly moral perspective it's fine.

**Comment by torokati44** [comment]
Okay, so I made it match the Chrome Badge, the rounded corners were somewhat out of place on the cornery website.

I think it looks better now:

image

Than with the original:

image

**Comment by Herschel** [comment]
Thank you!

**Pull request merged**
