### PR TITLE
fix: include the latest working release for all types

### PR DESCRIPTION
**Pull request by midgleyc**
We've had problems where the nightly web build fails due to Firefox not
signing, and it's nice to keep a working extension posted.

Untested.

### CODE REVIEW

**Comment by danielhjacobs** [comment]
This reduplicates a lot of code that I deduplicated in #53.

For the sake of deduplicating the releases code, I'd suggest:

- Changing releases.html to just be https://github.com/ruffle-rs/ruffle-rs.github.io/blob/master/_includes/releases.html#L21-L79
- Changing the assign lines to use `{% assign linux = assets | where_exp:"item", "item.name contains '-linux'" | first %}` etc.
- Adding back some code to https://github.com/ruffle-rs/ruffle-rs.github.io/blob/master/index.html#L215-L225
- Changing things like {% include releases.html releases=prerelease limit=3 %} to instead be {% include releases.html assets=assets=release.assets %}

I hope what I'm saying makes sense.

**Comment by midgleyc** [comment]
I'm not actually sure this will even work as written, I'd like to find a way to test it with the live `site.github.releases` (or at all!) before I work on refactoring it for cleanliness.

**Comment by danielhjacobs** [comment]
Fair enough. I never managed to test #53 either. The problem is I don't think I had permission to get the releases from Github, since I think it uses the Github API and I didn't have the key.

**Comment by danielhjacobs** [comment]
Based on the documentation there should be a : after the word map: https://shopify.github.io/liquid/filters/map/

**Comment by midgleyc** [comment]
Doesn't work as written: `map: "assets"` gives an array of arrays, and `flatten` doesn't exist as a plugin.

I found out I could test it with only `bundle exec jekyll serve`, and the earlier Nightly rows show up fine.

**Comment by midgleyc** [comment]
I have it working. `reverse` flattens an array of arrays, so if I `reverse` twice I get the flattening behaviour I want.

This isn't documented and so seems unstable, but my other solution also wants reverse, so I need to have it on the server to see if it works there.

**Pull request merged**
