### PR TITLE
avm2 update

### PR DESCRIPTION
**Pull request by evilpie**
Max points remains at 4560
Impl points changed from 3440 to 3467 (+27)
Stub penalty changed from 317 to 323 (+6)

### CODE REVIEW

**Comment by torokati44** [comment]
I hate to tell you, but this also brings up our API percentages to *69%* (76% including stubs).

**Comment by torokati44** [comment]
Huh, is that calculated automatically now? :astonished:

**Comment by danielhjacobs** [comment]
> Huh, is that calculated automatically now? 😲

It's here

https://github.com/ruffle-rs/ruffle-rs.github.io/blob/bfebfad52426ef1deedcf6c2635c4ba345ceb527/src/app/compatibility/page.tsx#L90

**Comment by danielhjacobs** [comment]
There's no reason it couldn't be calculated automatically. I think it's just not worth it to have that page use javascript.

**Comment by torokati44** [comment]
Ah, okay, thanks! I was just searching for it with "%", which is not there in the code.

**Comment by evilpie** [comment]
I thought it was automatic too, updated with 69% done 7% stubbed.

**Review by n0samu — APPROVED** [review]

**Review by torokati44 — APPROVED** [review]
I am once again expressing my annoying plea for a _little bit_ nicer commit message. :no_mouth:
Something like `Update AVM2 API progress` should be fine.

**Pull request merged**
